services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}                    #referencing .env file for these variables
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Mount volume to pgdata/
      - ./data:/app/data                   # Mount the data folder containing CSV files

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}             #again referencing .env file
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"  # Expose pgAdmin on port 5050
    depends_on:
      - db  # pgAdmin starts after the db container

  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

      
  # app:
  #   build: .
  #   depends_on:
  #     - db  # App container starts after the db container
  #   volumes:
  #     - ./data:/app/data            # Mount the data folder inside the app container
  #     - ./your_package:/app         # Mount package (scripts) inside the app container
  #   environment:
  #     - POSTGRES_HOST=db
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=mysecretpassword
  #     - POSTGRES_DB=bike_store
  #   command: ["tail -f /dev/null"]  # Start an interactive Bash shell on run