[project]
name = "sql-playground"
version = "1.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "psycopg[binary]>=3.2.8",
    "python-dotenv>=1.1.0",
    "ruff>=0.11.9",
]
