[project]
name = "sql-playground"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "pandas>=2.2.3",
    "psycopg[binary]>=3.2.8",
    "ruff>=0.11.9",
]
